config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :tenants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :tenant
  validates_uniqueness_to_tenant :name
end

app/models/tenant.rb
class Tenant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    set_current_tenant_by_subdomain_or_domain(:tenant, :subdomain, :domain)

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:tenant_id, :name)
    end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy ]

  # GET /tenants or /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1 or /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy

    respond_to do |format|
      format.html { redirect_to tenants_url, notice: "Tenant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:name, :subdomain, :domain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultitenantApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tenant_id, style: "display: block" %>
    <%= form.text_field :tenant_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Tenant:</strong>
    <%= project.tenant_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :subdomain, style: "display: block" %>
    <%= form.text_field :subdomain %>
  </div>

  <div>
    <%= form.label :domain, style: "display: block" %>
    <%= form.text_field :domain %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tenants/_tenant.html.erb
<div id="<%= dom_id tenant %>">
  <p>
    <strong>Name:</strong>
    <%= tenant.name %>
  </p>

  <p>
    <strong>Subdomain:</strong>
    <%= tenant.subdomain %>
  </p>

  <p>
    <strong>Domain:</strong>
    <%= tenant.domain %>
  </p>

</div>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Show this tenant", @tenant %> |
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tenants</h1>

<div id="tenants">
  <% @tenants.each do |tenant| %>
    <%= render tenant %>
    <p>
      <%= link_to "Show this tenant", tenant %>
    </p>
  <% end %>
</div>

<%= link_to "New tenant", new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tenant %>

<div>
  <%= link_to "Edit this tenant", edit_tenant_path(@tenant) %> |
  <%= link_to "Back to tenants", tenants_path %>

  <%= button_to "Destroy this tenant", @tenant, method: :delete %>
</div>